export const languageNames = {
  en: 'Anglais',
  fr: 'Français',
  es: 'Espagnol',
  it: 'Italien',
  de: 'Allemand',
  ja: 'Japonais',
  ko: 'Coréen',
  zh: 'Chinois',
  ru: 'Russe',
  pt: 'Portugais',
  hi: 'Hindi',
  ar: 'Arabe',
  da: 'Danois',
  hu: 'Hongrois',
  sv: 'Suédois',
  tr: 'Turc',
};